### ISSUE TITLE
error build with osqp1.0.0

### ISSUE THREAD

**Issue by lucafei** [robotology/osqp-eigen#188]
when i was building osqp-eigen 0.9.0 with osqp 1.0.0, some errors happened like following:
[ 20%] Building CXX object CMakeFiles/OsqpEigen.dir/src/Data.cpp.o
In file included from /home/mini/library/osqp-eigen/include/OsqpEigen/SparseMatrixHelper.hpp:17,
                 from /home/mini/library/osqp-eigen/include/OsqpEigen/Data.hpp:18,
                 from /home/mini/library/osqp-eigen/src/Data.cpp:12:
/home/mini/library/osqp-eigen/include/OsqpEigen/Compat.hpp: In function ‘OSQPCscMatrix* OsqpEigen::spalloc(OSQPInt, OSQPInt, OSQPInt)’:
/home/mini/library/osqp-eigen/include/OsqpEigen/Compat.hpp:89:5: error: ‘csc_set_data’ was not declared in this scope
   89 |     csc_set_data(M, m, n, M_nnz, M_x, M_i, M_p);
      |     ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/OsqpEigen.dir/build.make:79：CMakeFiles/OsqpEigen.dir/src/Data.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:110：CMakeFiles/OsqpEigen.dir/all] errors 2
make: *** [Makefile:136：all] errors 2

**Comment by traversaro** [comment]
Thanks for opening the issue! osqp 1.0.0 was release on (European) friday evening, we will probably handle this during next week.

**Comment by chuoru** [comment]
This problem is fixed in this pull request: https://github.com/robotology/osqp-eigen/pull/186
Please consider, thanks.

**Comment by traversaro** [comment]
Thanks @chuoru we had missed that PR!
